server2/competicoes/urls.py
from django.urls import path

from competicoes import Views
app_name = 'competicoes'
urlpatterns = [
    path('', Views.dashboard_hackathon, name='dashboard_hackathon'),
    # path('', Views.list_hackathon, name='list_hackathon'),
    path('new', Views.create_hackathon, name='create_hackathon'),
    path('update', Views.update_hackathon, name='update_hackathon'),
    path('get/<slug:hackathon>/<slug:team>', Views.get_hackathon, name='get_hackathon'),
    path('participe', Views.participe_hackathon, name='participe_hackathon'),
    path('phase', Views.create_phase, name='create_phase'),
    path('activity/new', Views.new_activity, name='new_activity'),
    path('activity/update', Views.update_activity, name='update_activity'),
    path('phase/get', Views.get_phase, name='get_phase')
]

server2/hackathon/urls.py
from django.conf.urls import url
from django.contrib import admin
from core import Views
from django.contrib.auth import views as auth_views
# from user import views
#from django.contrib.auth.views import login, logout
#from user.forms import UserAdminCreationForm
from django.urls import path, include
from rest_framework import routers
from rest_framework.authtoken import views

from team.Views import TeamViewSet

router = routers.DefaultRouter()
router.register(r'tarefas', TeamViewSet)

urlpatterns = [
    path('api/', include(router.urls)),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name="login"),
    path('logout/', Views.logout_view, name="logout"),
    path('register/', Views.register, name='register'),
    path('user/update/', Views.update_user, name='update_user'),
    path('register_commit/', Views.register_commit, name='register_commit'),
    url(r'^admin/', admin.site.urls),
    url(r'^$', Views.index, name='index'),
    url(r'^dashboard/', Views.dashboard, name='dashboard'),
    url(r'^settings/', Views.settings, name='settings'),
    path('team/', include("team.urls")),
    path('hackathon/', include("competicoes.urls", namespace="competicoes")),
    path('api-auth/', include('rest_framework.urls')),
    path('api-token-auth/', views.obtain_auth_token, name='api-token-auth')
]

server2/team/urls.py
from django.urls import path

from team import Views

urlpatterns = [
    path('', Views.list_team, name='list_teams'),
    path('new', Views.create_team, name='create_team'),
    path('delete', Views.delete_team, name='delete_team'),
    path('update', Views.update_team, name='update_team'),
    path('<slug:team>', Views.get_team, name='get_team'),
    path('invitation/new', Views.new_team_invitation, name='invitation_team'),
    path('invitation/response', Views.invitation_response, name='response_invitations_team')
]

server2/competicoes/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
from team.models import Team


class Activity(models.Model):
    id = models.AutoField(primary_key=True)
    id_team = models.ForeignKey(Team, on_delete=models.CASCADE, related_name="team")
    name = models.CharField(max_length=255)
    description = models.TextField()
    nota = models.IntegerField()

    def __str__(self):
        return_ = "Phase " + self.name + " enviada pelo Team " + self.id_team.name
        return return_


class Premium(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)
    description = models.TextField()
    winners = models.ManyToManyField(Activity)

    def __str__(self):
        return self.name


class Phase(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)
    description = models.TextField()
    activities = models.ManyToManyField(Activity)
    awards = models.ManyToManyField(Premium)

    def __str__(self):
        return self.name


class Hackathon(models.Model):
    slug = models.SlugField('Slug', unique=True)
    name = models.CharField(max_length=255)
    description = models.TextField()
    team_manager = models.ForeignKey(Team, on_delete=models.CASCADE, related_name="manager")
    teams = models.ManyToManyField(Team, through='Participation', related_name="teams")
    phases = models.ManyToManyField(Phase)

    def __str__(self):
        return self.name


class Participation(models.Model):
    id = models.AutoField(primary_key=True)
    id_hackathon = models.ForeignKey(Hackathon, on_delete=models.CASCADE)
    LEVEL_ASSES = (
        ('P', 'Participant'),
        ('D', 'Disqualified'),
        ('W', 'Winner'),
        {'I', 'Invited'}
    )
    level_asses = models.CharField(max_length=50, choices=LEVEL_ASSES)
    id_team = models.ForeignKey(Team, on_delete=models.CASCADE)

    def __str__(self):
        return self.id_team.slug

server2/core/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models
from team.models import  Team


# Create your models here.


class Notification(models.Model):
    id = models.AutoField(primary_key=True)
    id_user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    text = models.CharField(max_length=255)
    type_notification = models.CharField(max_length=255)

    def __str__(self):
        return self.name










server2/team/models.py
from django.contrib.auth.models import User
from django.db import models


class Team(models.Model):
    slug = models.SlugField('Slug', unique=True)
    name = models.CharField(max_length=255)
    description = models.TextField()
    status = models.TextField()
    #members = models.ManyToManyField(User, through='Member', related_name='members')

    def __str__(self):
        return self.name


class Member(models.Model):
    id = models.AutoField(primary_key=True)
    id_user = models.CharField(max_length=50)
    LEVEL_ASSES = (
        ('U', 'User'),
        ('A', 'Admin'),
        ('I', 'Invited')
    )
    level_asses = models.CharField(max_length=50, choices=LEVEL_ASSES)
    id_team = models.CharField(max_length=50)

    def __str__(self):
        return_ = "User " + self.id_user.username + " é " + self.level_asses + " do team " + self.id_team
        return return_


server2/competicoes/forms.py
from django.forms import ModelForm, Textarea

from competicoes.models import Activity, Premium, Phase, Hackathon


class FormActivity(ModelForm):
    class Meta:
        model = Activity
        fields = ["name", "description"]
        widgets = {
            'description': Textarea(attrs={'cols': 80, 'rows': 20}),
        }


class FormPremium(ModelForm):
    class Meta:
        model = Premium
        fields = ["name", "description"]
        widgets = {
            'description': Textarea(attrs={'cols': 80, 'rows': 20}),
        }


class FormPhase(ModelForm):
    class Meta:
        model = Phase
        fields = ["name", "description"]
        widgets = {
            'description': Textarea(attrs={'cols': 80, 'rows': 20}),
        }


class FormHackathon(ModelForm):
    class Meta:
        model = Hackathon
        fields = ["name", "description"]
        widgets = {
            'description': Textarea(attrs={'cols': 80, 'rows': 20}),
        }

server2/core/forms.py
from django.forms import ModelForm

from core.models import Notification


class FormNotification(ModelForm):
    class Meta:
        model = Notification
        fields = ["__all__"]

server2/team/forms.py
from django.forms import ModelForm, Textarea

from hackathon.team.models import Team, Member


class FormTeam(ModelForm):
    class Meta:
        model = Team
        fields = ["name", "description"]
        widgets = {
            'description': Textarea(attrs={'cols': 80, 'rows': 20}),
        }


class FormMember(ModelForm):
    class Meta:
        model = Member
        fields = ["level_asses", "id_user"]

server2/core/templates/_partial/fast_info.html
<div class="card card-statistics">
    <div class="card-body">
        <div class="d-flex flex-column flex-md-row align-items-center justify-content-between">
            <div class="statistics-item">
                <p>
                    <i class="icon-sm fa fa-user mr-2"></i>
                    New users
                </p>
                <h2>54000</h2>
                <label class="badge badge-outline-success badge-pill">2.7% increase</label>
            </div>
            <div class="statistics-item">
                <p>
                    <i class="icon-sm fas fa-hourglass-half mr-2"></i>
                    Avg Time
                </p>
                <h2>123.50</h2>
                <label class="badge badge-outline-danger badge-pill">30% decrease</label>
            </div>
            <div class="statistics-item">
                <p>
                    <i class="icon-sm fas fa-cloud-download-alt mr-2"></i>
                    Downloads
                </p>
                <h2>3500</h2>
                <label class="badge badge-outline-success badge-pill">12% increase</label>
            </div>
            <div class="statistics-item">
                <p>
                    <i class="icon-sm fas fa-check-circle mr-2"></i>
                    Update
                </p>
                <h2>7500</h2>
                <label class="badge badge-outline-success badge-pill">57% increase</label>
            </div>
            <div class="statistics-item">
                <p>
                    <i class="icon-sm fas fa-chart-line mr-2"></i>
                    Sales
                </p>
                <h2>9000</h2>
                <label class="badge badge-outline-success badge-pill">10% increase</label>
            </div>
            <div class="statistics-item">
                <p>
                    <i class="icon-sm fas fa-circle-notch mr-2"></i>
                    Pending
                </p>
                <h2>7500</h2>
                <label class="badge badge-outline-danger badge-pill">16% decrease</label>
            </div>
        </div>
    </div>
</div>

server2/core/templates/_partial/right_sidebar.html
<div id="right-sidebar" class="settings-panel">
            <i class="settings-close fa fa-times"></i>
            <ul class="nav nav-tabs" id="setting-panel" role="tablist">
                <li class="nav-item">
                    <a class="nav-link active" id="todo-tab" data-toggle="tab" href="#todo-section" role="tab"
                       aria-controls="todo-section" aria-expanded="true">TO DO LIST</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="chats-tab" data-toggle="tab" href="#chats-section" role="tab"
                       aria-controls="chats-section">CHATS</a>
                </li>
            </ul>
            <div class="tab-content" id="setting-content">
                <div class="tab-pane fade show active scroll-wrapper" id="todo-section" role="tabpanel"
                     aria-labelledby="todo-section">
                    <div class="add-items d-flex px-3 mb-0">
                        <form class="form w-100">
                            <div class="form-group d-flex">
                                <input type="text" class="form-control todo-list-input" placeholder="Add To-do">
                                <button type="submit" class="add btn btn-primary todo-list-add-btn" id="add-task-todo">
                                    Add
                                </button>
                            </div>
                        </form>
                    </div>
                    <div class="list-wrapper px-3">
                        <ul class="d-flex flex-column-reverse todo-list">
                            <li>
                                <div class="form-check">
                                    <label class="form-check-label">
                                        <input class="checkbox" type="checkbox">
                                        Team review meeting at 3.00 PM
                                    </label>
                                </div>
                                <i class="remove fa fa-times-circle"></i>
                            </li>
                            <li>
                                <div class="form-check">
                                    <label class="form-check-label">
                                        <input class="checkbox" type="checkbox">
                                        Prepare for presentation
                                    </label>
                                </div>
                                <i class="remove fa fa-times-circle"></i>
                            </li>
                            <li>
                                <div class="form-check">
                                    <label class="form-check-label">
                                        <input class="checkbox" type="checkbox">
                                        Resolve all the low priority tickets due today
                                    </label>
                                </div>
                                <i class="remove fa fa-times-circle"></i>
                            </li>
                            <li class="completed">
                                <div class="form-check">
                                    <label class="form-check-label">
                                        <input class="checkbox" type="checkbox" checked>
                                        Schedule meeting for next week
                                    </label>
                                </div>
                                <i class="remove fa fa-times-circle"></i>
                            </li>
                            <li class="completed">
                                <div class="form-check">
                                    <label class="form-check-label">
                                        <input class="checkbox" type="checkbox" checked>
                                        Project review
                                    </label>
                                </div>
                                <i class="remove fa fa-times-circle"></i>
                            </li>
                        </ul>
                    </div>
                    <div class="events py-4 border-bottom px-3">
                        <div class="wrapper d-flex mb-2">
                            <i class="fa fa-times-circle text-primary mr-2"></i>
                            <span>Feb 11 2018</span>
                        </div>
                        <p class="mb-0 font-weight-thin text-gray">Creating component page</p>
                        <p class="text-gray mb-0">build a js based app</p>
                    </div>
                    <div class="events pt-4 px-3">
                        <div class="wrapper d-flex mb-2">
                            <i class="fa fa-times-circle text-primary mr-2"></i>
                            <span>Feb 7 2018</span>
                        </div>
                        <p class="mb-0 font-weight-thin text-gray">Meeting with Alisa</p>
                        <p class="text-gray mb-0 ">Call Sarah Graves</p>
                    </div>
                </div>
                <!-- To do section tab ends -->
                <div class="tab-pane fade" id="chats-section" role="tabpanel" aria-labelledby="chats-section">
                    <div class="d-flex align-items-center justify-content-between border-bottom">
                        <p class="settings-heading border-top-0 mb-3 pl-3 pt-0 border-bottom-0 pb-0">Friends</p>
                        <small class="settings-heading border-top-0 mb-3 pt-0 border-bottom-0 pb-0 pr-3 font-weight-normal">
                            See All
                        </small>
                    </div>
                    <ul class="chat-list">
                        <li class="list active">
                            <div class="profile"><img src="images/faces/face1.jpg" alt="image"><span
                                    class="online"></span></div>
                            <div class="info">
                                <p>Thomas Douglas</p>
                                <p>Available</p>
                            </div>
                            <small class="text-muted my-auto">19 min</small>
                        </li>
                        <li class="list">
                            <div class="profile"><img src="images/faces/face2.jpg" alt="image"><span
                                    class="offline"></span></div>
                            <div class="info">
                                <div class="wrapper d-flex">
                                    <p>Catherine</p>
                                </div>
                                <p>Away</p>
                            </div>
                            <div class="badge badge-success badge-pill my-auto mx-2">4</div>
                            <small class="text-muted my-auto">23 min</small>
                        </li>
                        <li class="list">
                            <div class="profile"><img src="images/faces/face3.jpg" alt="image"><span
                                    class="online"></span></div>
                            <div class="info">
                                <p>Daniel Russell</p>
                                <p>Available</p>
                            </div>
                            <small class="text-muted my-auto">14 min</small>
                        </li>
                        <li class="list">
                            <div class="profile"><img src="images/faces/face4.jpg" alt="image"><span
                                    class="offline"></span></div>
                            <div class="info">
                                <p>James Richardson</p>
                                <p>Away</p>
                            </div>
                            <small class="text-muted my-auto">2 min</small>
                        </li>
                        <li class="list">
                            <div class="profile"><img src="images/faces/face5.jpg" alt="image"><span
                                    class="online"></span></div>
                            <div class="info">
                                <p>Madeline Kennedy</p>
                                <p>Available</p>
                            </div>
                            <small class="text-muted my-auto">5 min</small>
                        </li>
                        <li class="list">
                            <div class="profile"><img src="images/faces/face6.jpg" alt="image"><span
                                    class="online"></span></div>
                            <div class="info">
                                <p>Sarah Graves</p>
                                <p>Available</p>
                            </div>
                            <small class="text-muted my-auto">47 min</small>
                        </li>
                    </ul>
                </div>
                <!-- chat tab ends -->
            </div>
        </div>

server2/core/templates/_partial/sidebar.html
{% load static %}
<nav class="sidebar sidebar-offcanvas" id="sidebar">
    <ul class="nav">
        <li class="nav-item nav-profile">
            <div class="nav-link">
                <div class="profile-image">
                    <img src="{% static 'images/faces/face9.jpg' %}" alt="image"/>
                </div>
                <div class="profile-name">
                    <strong>Bem vindo</strong>
                    <p class="name">
                        {{ user.username }}
                    </p>
                </div>
            </div>
        </li>
        <!--<li class="nav-item">
            <a class="nav-link" href="{% url 'competicoes:dashboard_hackathon' %}">
                <i class="fa fa-puzzle-piece menu-icon"></i>
                <span class="menu-title">Meus Hackthons</span>
            </a>
        </li>-->
        <li class="nav-item">
            <a class="nav-link" href="{% url 'list_teams' %}">
                <i class="fas fa-tasks menu-icon text-info"></i>
                <span class="menu-title">Tarefas</span>
            </a>
{#            <a class="nav-link" data-toggle="collapse" href="#page-layouts" aria-expanded="false"#}
{#               aria-controls="page-layouts">#}
{#                <i class="fas fa-user-friends menu-icon"></i>#}
{#                <span class="menu-title">Equipes</span>#}
{#                <i class="menu-arrow"></i>#}
{#            </a>#}
{##}
{#            <div class="collapse" id="page-layouts">#}
{#                <ul class="nav flex-column sub-menu">#}
{#                    <li class="nav-item d-none d-lg-block"><a class="nav-link" href="{% url 'list_teams' %}">Times</a>#}
{#                    </li>#}
{#                    <li class="nav-item d-none d-lg-block"><a class="nav-link" href="team/">Time2</a>#}
{#                    </li>#}
{#                    <li class="nav-item d-none d-lg-block"><a class="nav-link" href="team/">Time3</a>#}
{#                    </li>#}
{#                    <li class="nav-item d-none d-lg-block"><a class="nav-link" href="team/">Time4</a>#}
{#                    </li>#}
{#                </ul>#}
{#            </div>#}
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">
                <i class="fas fa-frown menu-icon"></i>
                <span class="menu-title">Sair</span>
            </a>
        </li>
    </ul>
</nav>

server2/core/templates/_partial/top_navegation.html
{% load static %}
<nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row default-layout-navbar">
        <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
            <a class="navbar-brand brand-logo" href="{% url 'list_teams' %}"><img src="{% static 'images/logo.png' %}" alt="logo"/></a>
            <a class="navbar-brand brand-logo-mini" href="{% url 'list_teams' %}"><img src="{% static 'images/logoSmall.png' %}" alt="logo"/></a>
        </div>
        <div class="navbar-menu-wrapper d-flex align-items-stretch">
            <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
                <span class="fas fa-bars"></span>
            </button>

            <ul class="navbar-nav navbar-nav-right">
                <li class="nav-item nav-profile dropdown">
                    <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" id="profileDropdown">
                        <img src="{% static 'images/faces/face4.jpg' %}" alt="profile"/>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="profileDropdown">
                        <a class="dropdown-item" href="{% url 'settings' %}">
                            <i class="fas fa-cog text-primary"></i>
                            Configurações
                        </a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'logout' %}">
                            <i class="fas fa-power-off text-primary"></i>
                            Sair
                        </a>
                    </div>
                </li>
            </ul>
            <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button"
                    data-toggle="offcanvas">
                <span class="fas fa-bars"></span>
            </button>
        </div>
    </nav>